'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace WSTestReference
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ResponseJsonOfBEReglaValidacionExcluir", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ResponseJsonOfBEReglaValidacionExcluir
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private successField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private dataField() As WSTestReference.BEReglaValidacionExcluir
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private messageField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property success() As Boolean
            Get
                Return Me.successField
            End Get
            Set
                If (Me.successField.Equals(value) <> true) Then
                    Me.successField = value
                    Me.RaisePropertyChanged("success")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property data() As WSTestReference.BEReglaValidacionExcluir()
            Get
                Return Me.dataField
            End Get
            Set
                If (Object.ReferenceEquals(Me.dataField, value) <> true) Then
                    Me.dataField = value
                    Me.RaisePropertyChanged("data")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property message() As String
            Get
                Return Me.messageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.messageField, value) <> true) Then
                    Me.messageField = value
                    Me.RaisePropertyChanged("message")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="BEReglaValidacionExcluir", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class BEReglaValidacionExcluir
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private encuestaIDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private reglaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private comentarioField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private fechaRegistroField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property encuestaID() As Integer
            Get
                Return Me.encuestaIDField
            End Get
            Set
                If (Me.encuestaIDField.Equals(value) <> true) Then
                    Me.encuestaIDField = value
                    Me.RaisePropertyChanged("encuestaID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property regla() As String
            Get
                Return Me.reglaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.reglaField, value) <> true) Then
                    Me.reglaField = value
                    Me.RaisePropertyChanged("regla")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property comentario() As String
            Get
                Return Me.comentarioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.comentarioField, value) <> true) Then
                    Me.comentarioField = value
                    Me.RaisePropertyChanged("comentario")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property fechaRegistro() As String
            Get
                Return Me.fechaRegistroField
            End Get
            Set
                If (Object.ReferenceEquals(Me.fechaRegistroField, value) <> true) Then
                    Me.fechaRegistroField = value
                    Me.RaisePropertyChanged("fechaRegistro")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WSTestReference.WSTestSoap")>  _
    Public Interface WSTestSoap
        
        'CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/HelloWorld", ReplyAction:="*")>  _
        Function HelloWorld(ByVal request As WSTestReference.HelloWorldRequest) As WSTestReference.HelloWorldResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/HelloWorld", ReplyAction:="*")>  _
        Function HelloWorldAsync(ByVal request As WSTestReference.HelloWorldRequest) As System.Threading.Tasks.Task(Of WSTestReference.HelloWorldResponse)
        
        'CODEGEN: Generating message contract since element name sQuery from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/listarReglaValidacionExcluir", ReplyAction:="*")>  _
        Function listarReglaValidacionExcluir(ByVal request As WSTestReference.listarReglaValidacionExcluirRequest) As WSTestReference.listarReglaValidacionExcluirResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/listarReglaValidacionExcluir", ReplyAction:="*")>  _
        Function listarReglaValidacionExcluirAsync(ByVal request As WSTestReference.listarReglaValidacionExcluirRequest) As System.Threading.Tasks.Task(Of WSTestReference.listarReglaValidacionExcluirResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HelloWorldRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HelloWorld", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSTestReference.HelloWorldRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSTestReference.HelloWorldRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class HelloWorldRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HelloWorldResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HelloWorldResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSTestReference.HelloWorldResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSTestReference.HelloWorldResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class HelloWorldResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public HelloWorldResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HelloWorldResult As String)
            MyBase.New
            Me.HelloWorldResult = HelloWorldResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class listarReglaValidacionExcluirRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="listarReglaValidacionExcluir", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSTestReference.listarReglaValidacionExcluirRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSTestReference.listarReglaValidacionExcluirRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class listarReglaValidacionExcluirRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public sQuery As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal sQuery As String)
            MyBase.New
            Me.sQuery = sQuery
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class listarReglaValidacionExcluirResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="listarReglaValidacionExcluirResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSTestReference.listarReglaValidacionExcluirResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSTestReference.listarReglaValidacionExcluirResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class listarReglaValidacionExcluirResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public listarReglaValidacionExcluirResult As WSTestReference.ResponseJsonOfBEReglaValidacionExcluir
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal listarReglaValidacionExcluirResult As WSTestReference.ResponseJsonOfBEReglaValidacionExcluir)
            MyBase.New
            Me.listarReglaValidacionExcluirResult = listarReglaValidacionExcluirResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WSTestSoapChannel
        Inherits WSTestReference.WSTestSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WSTestSoapClient
        Inherits System.ServiceModel.ClientBase(Of WSTestReference.WSTestSoap)
        Implements WSTestReference.WSTestSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSTestReference_WSTestSoap_HelloWorld(ByVal request As WSTestReference.HelloWorldRequest) As WSTestReference.HelloWorldResponse Implements WSTestReference.WSTestSoap.HelloWorld
            Return MyBase.Channel.HelloWorld(request)
        End Function
        
        Public Function HelloWorld() As String
            Dim inValue As WSTestReference.HelloWorldRequest = New WSTestReference.HelloWorldRequest()
            inValue.Body = New WSTestReference.HelloWorldRequestBody()
            Dim retVal As WSTestReference.HelloWorldResponse = CType(Me,WSTestReference.WSTestSoap).HelloWorld(inValue)
            Return retVal.Body.HelloWorldResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSTestReference_WSTestSoap_HelloWorldAsync(ByVal request As WSTestReference.HelloWorldRequest) As System.Threading.Tasks.Task(Of WSTestReference.HelloWorldResponse) Implements WSTestReference.WSTestSoap.HelloWorldAsync
            Return MyBase.Channel.HelloWorldAsync(request)
        End Function
        
        Public Function HelloWorldAsync() As System.Threading.Tasks.Task(Of WSTestReference.HelloWorldResponse)
            Dim inValue As WSTestReference.HelloWorldRequest = New WSTestReference.HelloWorldRequest()
            inValue.Body = New WSTestReference.HelloWorldRequestBody()
            Return CType(Me,WSTestReference.WSTestSoap).HelloWorldAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSTestReference_WSTestSoap_listarReglaValidacionExcluir(ByVal request As WSTestReference.listarReglaValidacionExcluirRequest) As WSTestReference.listarReglaValidacionExcluirResponse Implements WSTestReference.WSTestSoap.listarReglaValidacionExcluir
            Return MyBase.Channel.listarReglaValidacionExcluir(request)
        End Function
        
        Public Function listarReglaValidacionExcluir(ByVal sQuery As String) As WSTestReference.ResponseJsonOfBEReglaValidacionExcluir
            Dim inValue As WSTestReference.listarReglaValidacionExcluirRequest = New WSTestReference.listarReglaValidacionExcluirRequest()
            inValue.Body = New WSTestReference.listarReglaValidacionExcluirRequestBody()
            inValue.Body.sQuery = sQuery
            Dim retVal As WSTestReference.listarReglaValidacionExcluirResponse = CType(Me,WSTestReference.WSTestSoap).listarReglaValidacionExcluir(inValue)
            Return retVal.Body.listarReglaValidacionExcluirResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSTestReference_WSTestSoap_listarReglaValidacionExcluirAsync(ByVal request As WSTestReference.listarReglaValidacionExcluirRequest) As System.Threading.Tasks.Task(Of WSTestReference.listarReglaValidacionExcluirResponse) Implements WSTestReference.WSTestSoap.listarReglaValidacionExcluirAsync
            Return MyBase.Channel.listarReglaValidacionExcluirAsync(request)
        End Function
        
        Public Function listarReglaValidacionExcluirAsync(ByVal sQuery As String) As System.Threading.Tasks.Task(Of WSTestReference.listarReglaValidacionExcluirResponse)
            Dim inValue As WSTestReference.listarReglaValidacionExcluirRequest = New WSTestReference.listarReglaValidacionExcluirRequest()
            inValue.Body = New WSTestReference.listarReglaValidacionExcluirRequestBody()
            inValue.Body.sQuery = sQuery
            Return CType(Me,WSTestReference.WSTestSoap).listarReglaValidacionExcluirAsync(inValue)
        End Function
    End Class
End Namespace
